USE RLU_TABLESAFE
GO
--Drop current data in temp tables
IF OBJECT_ID('D1117M_staging','U') IS NOT NULL DROP TABLE [D1117M_staging]; 
IF OBJECT_ID('D1993M_staging','U') IS NOT NULL DROP TABLE [D1993M_staging]; 
IF OBJECT_ID('D256M_staging','U') IS NOT NULL DROP TABLE [D256M_staging]; 
IF OBJECT_ID('D8500M_staging','U') IS NOT NULL DROP TABLE [D8500M_staging]; 
IF OBJECT_ID('D963M_staging','U') IS NOT NULL DROP TABLE [D963M_staging]; 
IF OBJECT_ID('D993M_staging','U') IS NOT NULL DROP TABLE [D993M_staging];  
IF OBJECT_ID('QM_DEV_TEAM.QMUL_VERIFIED_AS_NOT_DUPE_staging','U') IS NOT NULL DROP TABLE [QM_DEV_TEAM].[QMUL_VERIFIED_AS_NOT_DUPE_staging];
IF OBJECT_ID('QM_DEV_TEAM.QMUL_GRADE_CATEGORIES_staging','U') IS NOT NULL DROP TABLE [QM_DEV_TEAM].[QMUL_GRADE_CATEGORIES_staging];
IF OBJECT_ID('QM_DEV_TEAM.QMUL_FEED_EXCEPTIONS_staging','U') IS NOT NULL DROP TABLE [QM_DEV_TEAM].[QMUL_FEED_EXCEPTIONS_staging];
IF OBJECT_ID('QM_DEV_TEAM.QMUL_ALL_POTENTIAL_POSTS_DUPES_staging','U') IS NOT NULL DROP TABLE [QM_DEV_TEAM].[QMUL_ALL_POTENTIAL_POSTS_DUPES_staging];
GO
--Move data from RLU to temp tables
SELECT * INTO [dbo].[D1117M_staging] FROM [RLU].[dbo].D1117M;
GO
SELECT * INTO [dbo].[D1993M_staging]  FROM [RLU].[dbo].D1993M;
GO
SELECT * INTO [dbo].[D256M_staging] FROM [RLU].[dbo].D256M;
GO
SELECT * INTO [dbo].[D8500M_staging] FROM [RLU].[dbo].D8500M;
GO
SELECT * INTO [dbo].[D963M_staging] FROM [RLU].[dbo].D963M;
GO
SELECT * INTO [dbo].[D993M_staging] FROM [RLU].[dbo].D993M;
GO
SELECT * INTO [QM_DEV_TEAM].[QMUL_VERIFIED_AS_NOT_DUPE_staging] FROM [RLU].[QM_DEV_TEAM].[QMUL_VERIFIED_AS_NOT_DUPE];
GO
SELECT * INTO [QM_DEV_TEAM].[QMUL_GRADE_CATEGORIES_staging] FROM [RLU].[QM_DEV_TEAM].[QMUL_GRADE_CATEGORIES];
GO
SELECT * INTO [QM_DEV_TEAM].[QMUL_FEED_EXCEPTIONS_staging] FROM [RLU].[QM_DEV_TEAM].[QMUL_FEED_EXCEPTIONS];
GO
SELECT * INTO [QM_DEV_TEAM].[QMUL_ALL_POTENTIAL_POSTS_DUPES_staging] FROM [RLU].[QM_DEV_TEAM].[QMUL_ALL_POTENTIAL_POSTS_DUPES];
GO